% -------------------------------------------------------------------
%  Generated by MATLAB on 13-May-2017 00:26:20
%  MATLAB version: 8.5.0.197613 (R2015a)
% -------------------------------------------------------------------
saveVarsMat = load('test.mat');

v = saveVarsMat.v; % <29x127 double> too many elements

clear saveVarsMat;
